### ISSUE TITLE
InitProducer errors suppressed in wpwithinhandler.go

### ISSUE THREAD

**Issue by andybrodie** [WPTechInnovation/worldpay-within-sdk#115]
func (wp *WPWithinHandler) InitProducer(pspConfig map[string]string) (err error) inside wpwithinhandler.go won't return errors caused by invalid input data (e.g. missing HTE credentials).

This appears to be because the call to the underlying wp.wpwithin.InitProducer function is wrapped in a go func() call, which means that the wrapper function always returns nil, as specified outside of the go func() call.

**Comment by chackett** [comment]
@andybrodie , please see: 8512bfb47198f810a976c963b13b3ecacd646845

**Comment by chackett** [comment]
I have tested this. Will merge and close for now.
