### ISSUE TITLE
RPC Agent executable filename should be more predictable

### ISSUE THREAD

**Issue by andybrodie** [WPTechInnovation/worldpay-within-sdk#116]
Can we adopt a naming convention for RPC Agent executables please?  This will make it easier for wrapper developers to predict the name of the agent they should launch.

**Suggestion:** rpc-agent-_$os_-_$arch[.exe]

The $os and $arch conventions should use Go's cross-compiler options here: https://golang.org/doc/install/source#environment.  I.e. arm, arm64, 386, amd64 in our case.

However, the $os convention will cause problems for some wrappers.  The .NET wrapper, for example, can't (via a built-in mechanism) tell the difference between different flavours of Unix, instead only giving options of Unix, MacOSX, Windows.  (This might change once ported to .NET Core.)

**Comment by simbs** [comment]
I think we should specify a convention, then use it for all the wrappers. I believe these are the ones we have now:

rpc-agent-
    mac-64
    mac-32
    mac-arm64
    mac-arm32
    windows-64
    windows-32
    windows-arm64
    windows-arm32
    linux-64
    linux-32
    linux-arm32
    linux-arm64

Are these sufficient, or will we need different builds for different linux distros? If not, the wrapper should map all of them to linux.

**Comment by chackett** [comment]
No, let's just roll with Linux as the target for Linux OSs. I'm no expert, but I believe most linux distros all build on top the "Linux Kernel".

@andybrodie has said `arm` which matches Go's convention but is slightly ambiguous. Let's go with what @simbs (Mary) has said and use arm32.

In theory, we should be appending something like `386` and `amd64` for 32/64 bit builds as opposed to simple `32` or `64`. In fact, now that we are engaged in this conversation I am inclined to go with this. So I propose:

`rpc-agent-darwin-386
rpc-agent-darwin-amd64
rpc-agent-windows-386.exe
rpc-agent-windows-amd64.exe
rpc-agent-linux-386
rpc-agent-linux-amd64
rpc-agent-linux-arm32
rpc-agent-linux-arm64`

Please note this is an updated list of builds that I will be creating and should be supported by the launchers. You will notice the following:
- Removed Windows ARM builds as Go currently does not support this as per the Andys link.
- Removed Darwin ARM as the concept of launching a process separate to the main app on iOS will not work. For iOS to work we will need to compile a shared object that will be called from ObjC/Swift and Thrift will not play a part in this so for this scenario the RPC-Agent will be redundant.

And here are the articles I have been looking for. Confusing right.

https://en.wikipedia.org/wiki/X86-64
https://en.wikipedia.org/wiki/IA-32

**Comment by chackett** [comment]
@andybrodie what is the underscore in

` rpc-agent-$os-_$arch[.exe]` ??

Also, as we are only support Linux, let's assume that Unix means Linux. While I know Mac OS is Unix, we are lucky that Mac OS is reported separately. What are the chances of running into problems with this?

**Comment by andybrodie** [comment]
The underscore was accidental, i.e. me messing up markdown.

**Comment by chackett** [comment]
@andybrodie Is this done by you? Shall I close?

**Comment by andybrodie** [comment]
Yes, looks great.
