### ISSUE TITLE
RPC Agent build doesn't create executable that matches what wrappers search for

### ISSUE THREAD

**Issue by andybrodie** [WPTechInnovation/worldpay-within-sdk#118]
Currently "go install" creates rpc-agent.exe (on Windows) and puts it in to $GO_PATH/bin.  However, the wrappers will look for an RPC Agent named for the platform and architecture.

There is a shell script, build-all.sh, so perhaps the instructions in README.md at the top need to include, under "Install the RPC agent" to make a note that the agent needs to be renamed according to architecture; or to use build-all.sh

**Comment by chackett** [comment]
Great spot @andybrodie

**Comment by chackett** [comment]
Addressed at 38800225210879c2b643308c5f288530dbf280a7
