### ISSUE TITLE
v0.3 Third Dev Preview ZIP contains Mac OS metafiles

### ISSUE THREAD

**Issue by andybrodie** [WPTechInnovation/worldpay-within-sdk#119]
wpwithin-bins-0.3-release.zip contains Mac OS metafiles:

/_MACOSX
/wpwithin-bins-0.3-release/.DS_Store
/wpwithin-bins-0.3-release/rpc-agent.zip/_MACOSX
/wpwithin-bins-0.3-release/rpc-agent.zip/rpc-agent/.DS_Store

**Comment by chackett** [comment]
Ahh, good point, not sure how to remove these if building from my Mac.

**Comment by chackett** [comment]
I tried this command `zip -r -X Archive.zip *`

[rpc-agent-test-bins.zip](https://github.com/WPTechInnovation/worldpay-within-sdk/files/758137/rpc-agent-test-bins.zip)

**Comment by chackett** [comment]
@andybrodie Has tested out an archive created with the above command. I will be sure to use that when manually building releases on my machine, actually, I will add it to the build-all.sh script.
