### ISSUE TITLE
Simplification of SDK for developers proposal

### ISSUE THREAD

**Issue by kevingordonwp** [WPTechInnovation/worldpay-within-sdk#128]
This discussion focuses mainly on the python 2.7 wrapper initially. At the latest Atlanta hackathon it took up to 1/2 hour to setup each raspberry pi to work with the python 2.7 SDK. I was able to reduce this to under 3 minutes.

How?

I created 3 repos, one with the go-core in it, one with the rpc-binaries, and one with the python 2.7 sdk (wrapper in it). From a user facing point of view, let's not call them wrappers, let's call the wrapper the SDK, and protect them from any knowledge of the rpc-agent or SDK.

Then all I do is:

1) Pull down the python 2.7 SDK repo (containing submodules that point to the binary repo, and the thrift repo)
2) Run a setup.py script, which updates the git submodule repos, runs the thrift install and a few other small configs.
3) The develop should input their credentials for the payments system.

That's it!

After a convo with Conor he proposes a refinement of the above:

- Just two repos total; the go-core and the sdk (containing all the wrappers).
- Rather than have the binaries in a separate repo, pull these down from the release
- Don't have a repo per 'wrapper' have all the wrappers in one repo

What do people think?

**Comment by kevingordonwp** [comment]
In addition I'd like to streamline the Java process for getting it running on a Pi...

**Comment by simbs** [comment]
I think it should be a repo per wrapper. Documentation is enough to link them, and people shouldn't have to download 4 languages just to get the one they want. Plus, if development of one of them goes stale, it won't create confusion on which version is master.

**Comment by kevingordonwp** [comment]
I agree with you, though I also agree with @chackett view that 4 repos, would mean repeating issues, and more management overhead.

**Comment by simbs** [comment]
I think we can keep people from adding issues to the wrapper's repos to keep management in one place.

**Comment by kevingordonwp** [comment]
This is now covered by the work being done on issue #137 - therefore closing this as a duplicate
