### ISSUE TITLE
Web based app for creating sample apps.

### ISSUE THREAD

**Issue by chackett** [WPTechInnovation/worldpay-within-sdk#132]
Estimote have a cool web app for creating boilerplate apps with custom details such as beacon id, app name etc. Once configured you download the source project.. -> neat!

https://cloud.estimote.com/#/apps/add

I wonder is there any value in this for WPW... would be awesome for getting devs up and running! A nice show piece.

**Comment by kevingordonwp** [comment]
Heya, is that link correct, I just get a login page?

**Comment by chackett** [comment]
Ahh ok. Yes it is correct but probably need to login first.

**Comment by chackett** [comment]
FWIW - This is a harebrained idea and should be at the bottom of our priorities list. Still a cool feature though :)

Going to close for now...
