### ISSUE TITLE
Include support for existing web socket logger

### ISSUE THREAD

**Issue by chackett** [WPTechInnovation/worldpay-within-sdk#17]
Kevin developed a hook for Logrus where Go can log out to a Websocket connection, allowing log statements to be viewed in a web browser.

We need to think about how this will be included and supported by the SDK.

**Comment by kevingordonwp** [comment]
scheduled for Wednesday 24th now :)

**Comment by chackett** [comment]
This is done... can add the following configuration to SDK Config file.

`{
	"key": "wsLogEnable",
	"value": "true"
}, {
	"key": "wsLogPort",
	"value": "8182"
}, {
	"key": "wsLogLevel",
	"value": "debug,error,fatal"
}`
