### ISSUE TITLE
Add Andy B. and Mustafa K. feedback

### ISSUE THREAD

**Issue by chackett** [WPTechInnovation/worldpay-within-sdk#23]
Andy and Mustafa provided valuable feedback that needs to be tracked.

This is currently in a CSV file. I have part written a tool that will parse this CSV and upload each item into this repository as an issue. It will use an API key from Andy and Mustafa so it will be added from their accounts.

**Comment by kevingordonwp** [comment]
Okay, sounds cool. However most of these are going to be captured internally on our Trello board @chackett so if you don't have any objections I shall close this one.

**Comment by kevingordonwp** [comment]
All this content has been captured on our internal backlog - and will be raised as issues where appropriate so closing.

**Comment by kevingordonwp** [comment]
As per comment - these will be dealt with separately
