### ISSUE TITLE
node JS RPC agent

### ISSUE THREAD

**Issue by meetreks** [WPTechInnovation/worldpay-within-sdk#58]
Hi Ya,

I started a RPC agent manually in port 9090. This is using the GO src files present in the repository and I managed to install all dependencies as well.

Now I am trying to check the wrapper samples present under the wrapper directory. As instructed, I have changed the port there to 9091.

When i execute the main.js file, I am getting an error like "cannot file module thrift"

Can you throw some light as I am not able to figure this out.

Cheers,
Ram

**Comment by chackett** [comment]
Hi there,

Good work! You will need to install the Thrift node module using `npm install thrift` for this to work. 

Conor

**Comment by meetreks** [comment]
Hi Conor
,
Did exactly that and still the same issue.
Do you need to do something once the thrift install completes?

Regards,
Ram

**Comment by meetreks** [comment]
This is the exact error I am getting..

C:\Go\src\github.com\wptechinnovation\worldpay-within-sdk\wrappers\nodejs\exampl
es\sample-consumer>node main.js
Caught error: Error: Cannot find module 'thrift'
createClient.callback
createClient.callback.err: Error: Cannot find module 'thrift'
createClient.callback.response: null
C:\Go\src\github.com\wptechinnovation\worldpay-within-sdk\wrappers\nodejs\exampl
es\sample-consumer\main.js:14
client.setup("NodeJS-Device", "Sample NodeJS consumer device", function(err, res
ponse){
      ^

TypeError: Cannot read property 'setup' of undefined
    at Object.<anonymous> (C:\Go\src\github.com\wptechinnovation\worldpay-within
-sdk\wrappers\nodejs\examples\sample-consumer\main.js:14:7)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by meetreks** [comment]
This is the RPC agent which is running at 9091

C:\Go\bin>rpc-agent -port=9091
time="2016-09-04T09:19:55+01:00" level=debug msg="Begin main()"
time="2016-09-04T09:19:55+01:00" level=debug msg="Before initArgs()."
time="2016-09-04T09:19:55+01:00" level=debug msg="Begin initArgs()"
time="2016-09-04T09:19:55+01:00" level=debug msg="Before flag.parse()"
time="2016-09-04T09:19:55+01:00" level=debug msg="After flag.parse()"
time="2016-09-04T09:19:55+01:00" level=debug msg="Before log setup"
time="2016-09-04T09:19:55+01:00" level=debug msg="Begin parsing log level argume
nts"
Transport: *thrift.TServerSocket
Starting the rpc server on...: 127.0.0.1:9091

**Comment by chackett** [comment]
I am not too familiar with Node.JS unfortunately but I believe the issue is that there are multiple places that a Node.JS module can be installed when you instal it.

I think you may have installed the module in a place that our Node.JS app cannot access it. Can you please see if you can install the module globally.

http://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows

**Comment by meetreks** [comment]
Actually I have installed it globally. My modules was installed in 

%AppData%\Roaming\npm\node_modules

and I can clearly see thrift downloaded. 

I even copied thrift to the local directory where I am executing main.JS file present under consumer_samples and this is where it fails.

Actually node does search for npm_modules and looks for it

**Comment by chackett** [comment]
Ok, I am sorry for the trouble but I will need to test on Windows and try to re-create.

Up to now, I have been running on a mac.

**Comment by meetreks** [comment]
Thanks Conor, that will be helpful. Guess will be a trivial issue I guess. May be an explicit require and asking to point thrift to the lib may be a solution. Let me know. 

Btw, I have the go version so I am happily dabbling through, but will be helpful if you can help me sort this out.

**Comment by chackett** [comment]
Hi There Ram,

I have had a look at this and it is working fine for me.

I followed the following steps:
* Install Node.JS using installer binary from Node.JS site
* While inside the `c:\users\Worldpay` folder issue `node install thrift`
* Realise oops, didn't do global install, now issue `npm install -g thrift`
* cd into directory where Node.JS consumer is i.e. `..../wrapper/nodejs/examples/sample-consumer`
* execute command `node main.js` with the main.js code update to connect to the port that RPC-Agent is listening on.
* Application works and makes payment to producer running on another machine.

It looks like it just worked for me so there must be some kind of environmental problem on your end. Perhaps you could write some sample code outside of the WPWithin SDK to test your installation and how it consumed dependencies.

Regards,
Conor

**Comment by meetreks** [comment]
OK figured it out
did a npm uninstall thrift and npm cache clean (just in case)
Now I installed npm install -g thrift
did not work..

Then moved the SDK kit to thrift lib and started the consumer
worked as a treat

Thanks for the support

**Comment by chackett** [comment]
Good for you and no problem - what i'm here for.
