### ISSUE TITLE
runRPCAgent waits for process to complete

### ISSUE THREAD

**Issue by simbs** [WPTechInnovation/worldpay-within-sdk#60]
In the Python wrapper, the RPC Agent launcher will wait for the called process to complete. Since the launcher is meant to stay running, the rest of the code never executes.

**Comment by chackett** [comment]
@simbs @salihoztop - How is this going? Resolved?

**Comment by simbs** [comment]
Resolved b7e25c9b8137468e152281895833881daea9dac5
