### ISSUE TITLE
TotalPriceResponse has int TotalAmount instead of Price

### ISSUE THREAD

**Issue by andybrodie** [WPTechInnovation/worldpay-within-sdk#67]
The TotalPriceResponse has a TotalAmount, should re-use the Price structure to keep currency and amount together.

**Comment by chackett** [comment]
As discussed, the `Price` structure is not appropriate as it contains various other pieces of information. The correct structure is aPricePerUnit` but is inappropriately named. It would be extra effort to refactor everything so we are just going to go ahead and add `currencyCode` as a field to the `TotalPriceResponse` structure in Thrift.

**Comment by chackett** [comment]
Update thrift a879d6ca5bf6f05f2e34eb068495e7df16f8fcde

I need to update the Node.JS and Java wrappers + Go SDK core to set this field.

**Comment by chackett** [comment]
Reopening as a reminder that I need to make updates :)

**Comment by chackett** [comment]
Done 👍
