### ISSUE TITLE
PriceQuote - TotalPrice returning as 0

### ISSUE THREAD

**Issue by santhosh0705** [WPTechInnovation/worldpay-within-sdk#95]
Hi,

I tried executing the consumer example in java wrapper. on getServicePriceQuote.

`WWTotalPriceResponse tpr = wpw.selectService(serviceId, numberOfUnits, priceId);`

tpr.getTotalPrice() -- Is always returning as 0.
But in payment response, its currently returning the total amount.

**Comment by kevingordonwp** [comment]
Thank you for finding this, we will investigate and get back to you over the next couple of days.
